-- eSewa Payment Integration - Database Migration
-- Run this SQL script in phpMyAdmin to create the payment_logs table

-- Create payment_logs table to store all payment transactions
CREATE TABLE IF NOT EXISTS `payment_logs` (
    `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Unique identifier for payment log entry',
    `student_name` VARCHAR(100) NOT NULL COMMENT 'Name of the student making payment',
    `student_email` VARCHAR(100) NOT NULL COMMENT 'Email address of the student',
    `transaction_uuid` VARCHAR(100) UNIQUE NOT NULL COMMENT 'Unique transaction ID generated by our system',
    `amount` DECIMAL(10, 2) NOT NULL COMMENT 'Amount paid in NPR',
    `status` VARCHAR(20) DEFAULT 'PENDING' COMMENT 'Payment status: PENDING, COMPLETE, FAILED, REFUNDED',
    `ref_id` VARCHAR(50) COMMENT 'Reference ID from eSewa (transaction_code)',
    `payment_method` VARCHAR(50) DEFAULT 'ESEWA' COMMENT 'Payment method used',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When payment was initiated',
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    `notes` TEXT COMMENT 'Additional notes about the transaction',
    KEY `idx_transaction_uuid` (`transaction_uuid`),
    KEY `idx_student_email` (`student_email`),
    KEY `idx_status` (`status`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stores all eSewa payment transaction logs';

-- (Optional) Create settings table to store configurable values like admission fee
CREATE TABLE IF NOT EXISTS `settings` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `key` VARCHAR(100) UNIQUE NOT NULL,
    `value` VARCHAR(500) NOT NULL,
    `description` TEXT,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_key` (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default admission fee setting
INSERT IGNORE INTO `settings` (`key`, `value`, `description`) 
VALUES ('admission_fee', '100.00', 'Default admission fee for student registration');

-- (Optional) View for payment statistics
CREATE OR REPLACE VIEW payment_statistics AS
SELECT 
    DATE(created_at) as payment_date,
    status,
    COUNT(*) as total_transactions,
    SUM(amount) as total_amount,
    AVG(amount) as average_amount
FROM payment_logs
GROUP BY DATE(created_at), status
ORDER BY payment_date DESC;

-- Create pre-admission applications table to store student registration forms
CREATE TABLE IF NOT EXISTS `pre_admission` (
    `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Unique identifier for pre-admission entry',
    `student_name` VARCHAR(150) NOT NULL COMMENT 'Full name of the student',
    `student_email` VARCHAR(100) NOT NULL COMMENT 'Email address of the student',
    `father_name` VARCHAR(150) NOT NULL COMMENT 'Father\'s full name',
    `mother_name` VARCHAR(150) COMMENT 'Mother\'s full name',
    `phone` VARCHAR(20) COMMENT 'Contact phone number',
    `gender` VARCHAR(20) COMMENT 'Student gender (Male, Female, Other)',
    `date_of_birth` DATE COMMENT 'Student date of birth',
    `address` TEXT COMMENT 'Residential address (City, District, Province)',
    `admission_fee` DECIMAL(10, 2) DEFAULT 100.00 COMMENT 'Admission fee amount',
    `application_status` VARCHAR(30) DEFAULT 'PENDING' COMMENT 'Status: PENDING, PROCESSING, APPROVED, REJECTED, PAID',
    `payment_status` VARCHAR(20) DEFAULT 'PENDING' COMMENT 'Payment status: PENDING, COMPLETE, FAILED',
    `transaction_uuid` VARCHAR(100) COMMENT 'Reference to payment_logs transaction',
    `notes` TEXT COMMENT 'Admin notes about the application',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When application was submitted',
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update time',
    KEY `idx_student_email` (`student_email`),
    KEY `idx_application_status` (`application_status`),
    KEY `idx_created_at` (`created_at`),
    KEY `idx_transaction_uuid` (`transaction_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stores student pre-admission applications';
